# LocaNext Build Pipeline - Gitea Actions
# Internal builds with release creation
# DUAL PUSH REQUIRED: git push origin main && git push gitea main

name: Build LocaNext

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:  # Manual trigger

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'

jobs:
  # ============================================
  # JOB 1: Test Backend
  # ============================================
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Create admin user
        run: python3 scripts/create_admin.py

      - name: Start server
        run: |
          python3 server/main.py &
          sleep 5

      - name: Run tests
        run: RUN_API_TESTS=1 python3 -m pytest -v --tb=short
        env:
          PYTHONPATH: .

  # ============================================
  # JOB 2: Build Windows Installer
  # ============================================
  build-windows:
    needs: test
    runs-on: windows-latest  # Requires Windows self-hosted runner
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(python3 -c "from version import SEMANTIC_VERSION; print(SEMANTIC_VERSION)")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Install dependencies
        working-directory: locaNext
        run: npm ci

      - name: Check version
        run: python scripts/check_version_unified.py

      - name: Build Electron app
        working-directory: locaNext
        run: npm run build:win

      - name: List build output
        run: ls -la locaNext/dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: locanext-windows
          path: |
            locaNext/dist/*.exe
            locaNext/dist/latest.yml

  # ============================================
  # JOB 3: Create Gitea Release
  # ============================================
  release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: locanext-windows
          path: ./dist

      - name: List artifacts
        run: ls -la ./dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build-windows.outputs.version }}
          name: LocaNext v${{ needs.build-windows.outputs.version }}
          body: |
            ## LocaNext v${{ needs.build-windows.outputs.version }}

            Built from Gitea Actions.

            ### Download
            - `LocaNext-Setup.exe` - Windows Installer

            ### Auto-Update
            Desktop apps will auto-detect this update on next launch.
          files: |
            ./dist/*.exe
            ./dist/latest.yml
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Also update 'latest' tag for generic provider
      - name: Update latest tag
        run: |
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.local"
          git tag -f latest
          git push -f origin latest
        continue-on-error: true
