#!/usr/bin/env python3
"""
PostgreSQL Configuration Generator for LocaNext

Generates optimized postgresql.conf based on server RAM.

Usage:
    python3 scripts/generate_postgresql_config.py --ram 32
    python3 scripts/generate_postgresql_config.py --ram 16 --output /tmp/postgresql.conf
    python3 scripts/generate_postgresql_config.py --ram 64 --ssd false
"""

import argparse
from pathlib import Path


def generate_config(ram_gb: int, is_ssd: bool = True, max_connections: int = 200) -> str:
    """
    Generate PostgreSQL configuration based on server specs.

    Args:
        ram_gb: Server RAM in GB
        is_ssd: Whether using SSD (vs HDD)
        max_connections: Maximum database connections

    Returns:
        Configuration file content as string
    """
    # Memory calculations
    shared_buffers = ram_gb // 4  # 25% of RAM
    effective_cache_size = (ram_gb * 3) // 4  # 75% of RAM
    work_mem = (ram_gb * 1024) // 128  # RAM / 128 in MB
    maintenance_work_mem = ram_gb // 16  # RAM / 16 in GB

    # Ensure minimums
    shared_buffers = max(shared_buffers, 1)
    work_mem = max(work_mem, 64)
    maintenance_work_mem = max(maintenance_work_mem, 1)

    # SSD vs HDD settings
    if is_ssd:
        random_page_cost = "1.1"
        effective_io_concurrency = "200"
    else:
        random_page_cost = "4.0"
        effective_io_concurrency = "2"

    # Parallel workers based on typical CPU (assume 2 cores per 8GB RAM)
    cpu_cores = max(ram_gb // 4, 2)
    max_parallel_workers = min(cpu_cores, 16)
    max_parallel_workers_per_gather = min(cpu_cores // 2, 8)

    config = f"""# ============================================================================
# PostgreSQL Configuration - Auto-Generated for {ram_gb}GB RAM Server
# ============================================================================
# Generated by: scripts/generate_postgresql_config.py
# Target: 100+ concurrent users, bulk uploads, {"NVMe SSD" if is_ssd else "HDD"}
#
# USAGE:
#   sudo cp this_file.conf /etc/postgresql/16/main/postgresql.conf
#   sudo systemctl restart postgresql
# ============================================================================

# ----------------------------------------------------------------------------
# CONNECTION SETTINGS
# ----------------------------------------------------------------------------
max_connections = {max_connections}
superuser_reserved_connections = 3

# ----------------------------------------------------------------------------
# MEMORY SETTINGS (calculated for {ram_gb}GB RAM)
# ----------------------------------------------------------------------------
shared_buffers = {shared_buffers}GB
effective_cache_size = {effective_cache_size}GB
work_mem = {work_mem}MB
maintenance_work_mem = {maintenance_work_mem}GB

# ----------------------------------------------------------------------------
# WRITE-AHEAD LOG (WAL)
# ----------------------------------------------------------------------------
wal_buffers = {min(shared_buffers * 32, 256)}MB
checkpoint_completion_target = 0.9
checkpoint_timeout = 15min
max_wal_size = {min(shared_buffers, 8)}GB
min_wal_size = 1GB

# ----------------------------------------------------------------------------
# STORAGE OPTIMIZATION ({"SSD" if is_ssd else "HDD"})
# ----------------------------------------------------------------------------
random_page_cost = {random_page_cost}
effective_io_concurrency = {effective_io_concurrency}

# ----------------------------------------------------------------------------
# PARALLEL QUERY (estimated {cpu_cores} CPU cores)
# ----------------------------------------------------------------------------
max_parallel_workers_per_gather = {max_parallel_workers_per_gather}
max_parallel_workers = {max_parallel_workers}
max_parallel_maintenance_workers = {max(max_parallel_workers_per_gather, 2)}

# ----------------------------------------------------------------------------
# BULK INSERT OPTIMIZATION
# ----------------------------------------------------------------------------
synchronous_commit = off
commit_delay = 10000

# ----------------------------------------------------------------------------
# QUERY PLANNER
# ----------------------------------------------------------------------------
default_statistics_target = 100

# ----------------------------------------------------------------------------
# LOGGING
# ----------------------------------------------------------------------------
log_min_duration_statement = 1000
log_checkpoints = on
log_connections = off
log_disconnections = off

# ----------------------------------------------------------------------------
# AUTOVACUUM
# ----------------------------------------------------------------------------
autovacuum = on
autovacuum_max_workers = {min(max_parallel_workers_per_gather, 4)}
autovacuum_naptime = 30s
autovacuum_vacuum_scale_factor = 0.1
autovacuum_analyze_scale_factor = 0.05

# ============================================================================
# Configuration Summary
# ============================================================================
# RAM: {ram_gb}GB
# Storage: {"SSD" if is_ssd else "HDD"}
# Max Connections: {max_connections}
# Shared Buffers: {shared_buffers}GB (25% of RAM)
# Effective Cache: {effective_cache_size}GB (75% of RAM)
# Work Memory: {work_mem}MB per operation
# Parallel Workers: {max_parallel_workers}
# ============================================================================
"""
    return config


def main():
    parser = argparse.ArgumentParser(
        description="Generate PostgreSQL configuration for LocaNext"
    )
    parser.add_argument(
        "--ram", type=int, required=True,
        help="Server RAM in GB (e.g., 16, 32, 64)"
    )
    parser.add_argument(
        "--ssd", type=str, default="true",
        help="Using SSD storage? (true/false, default: true)"
    )
    parser.add_argument(
        "--connections", type=int, default=200,
        help="Max database connections (default: 200)"
    )
    parser.add_argument(
        "--output", type=str, default=None,
        help="Output file path (default: prints to stdout)"
    )

    args = parser.parse_args()

    is_ssd = args.ssd.lower() in ("true", "yes", "1")
    config = generate_config(args.ram, is_ssd, args.connections)

    if args.output:
        output_path = Path(args.output)
        output_path.write_text(config)
        print(f"[OK] Configuration written to: {output_path}")
        print(f"     RAM: {args.ram}GB | SSD: {is_ssd} | Connections: {args.connections}")
    else:
        print(config)


if __name__ == "__main__":
    main()
